sudo: true

services:
  - docker

before_install:
  - travis_retry docker build -t chocobozzz/peertube .
  - docker run -d --publish=9000:9000 chocobozzz/peertube

script:
  - sleep 300 && curl http://localhost:9000

