sudo: true

services:
  - docker

before_install:
  - travis_retry docker build -t chocobozzz/peertube .
  - docker run --publish=9000:9000 yourname/peertube

script:
  - sleep 100 && curl http://localhost:9000

